# Generated by Django 3.1.1 on 2020-09-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='jobs',
            table='works_jobs',
        ),
    ]
