# Generated by Django 3.1.1 on 2020-09-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20200930_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='image',
            field=models.BinaryField(),
        ),
    ]
